version: "2.1"

services:
  app:
    image: gradle:4.7-jdk8
    command: sleep infinity
    working_dir: /home/gradle/project
    #command: gradle clean bootRun
    depends_on:
    - maindb
    - redis
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    - MYSQL_HOST=maindb
    - DB_NAME=motion_portal_db
    - DB_USER=www
    - DB_PASSWORD=wwwpwd
    - REDIS_HOST=redis
    - KAFKA_HOSTS=kafka:9092
    - SERVER_PORT=8080
    volumes:
    - .:/home/gradle/project
    - ./.gradle:/home/gradle/.gradle



  maindb:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root1234
    - MYSQL_DATABASE=motion_portal_db
    - MYSQL_USER=www
    - MYSQL_PASSWORD=wwwpwd
    volumes:
    - ./src/main/db/migration/:/docker-entrypoint-initdb.d/


  redis:
    image: redis:3-alpine

  kafka:
    image: spotify/kafka:latest
    environment:
      - "ADVERTISED_PORT=9092"
