CREATE TABLE `mall_product_category` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uuid` char(36) NOT NULL DEFAULT '' COMMENT 'uuid',
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1,树鱼直充；2，树鱼卡密；3，自定义',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '名字',
  `category_code` varchar(12) NOT NULL DEFAULT '' COMMENT '分类代码',
  `sort` bigint(20) DEFAULT NULL COMMENT '排序',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '启用/禁用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `created_at` (`created_at`),
  KEY `updated_at` (`updated_at`),
  KEY `enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mall_product` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uuid` char(36) NOT NULL DEFAULT '' COMMENT 'uuid',
  `icon_url` varchar(128) NOT NULL DEFAULT ''COMMENT '图标',
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1,树鱼直充；2，树鱼卡密；3，自定义',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '名字',
  `short_desc` varchar(255) NOT NULL DEFAULT '' COMMENT '短描述',
  `category_code` varchar(12) NOT NULL DEFAULT '' COMMENT '分类代码',
  `product_id` varchar(20) NOT NULL DEFAULT '' COMMENT '商品代码',
  `price` double NOT NULL COMMENT '单价',
  `currency` char(3) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `discount` float DEFAULT NULL COMMENT '折扣',
  `description` text COMMENT '商品描述',
  `sort` bigint(20) DEFAULT NULL COMMENT '排序',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '启用/禁用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `created_at` (`created_at`),
  KEY `updated_at` (`updated_at`),
  KEY `sort` (`sort`),
  KEY `category_code` (`category_code`),
  KEY `product_id` (`product_id`),
  KEY `type` (`type`),
  KEY `enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `mall_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uuid` char(36) NOT NULL DEFAULT '' COMMENT 'uuid',
  `order_id` varchar(128) NOT NULL DEFAULT ''COMMENT '订单编号',
  `user_id` bigint(20) unsigned NOT NULL COMMENT '用户ID'
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '商品类型：1,树鱼直充；2，树鱼卡密；3，自定义',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '名字',
  `category_code` varchar(12) NOT NULL DEFAULT '' COMMENT '分类代码',
  `product_id` varchar(20) NOT NULL DEFAULT '' COMMENT '商品代码',
  `amount` int(10) NOT NULL DEFAULT 1 COMMENT '商品数量',
  `price` double NOT NULL COMMENT '单价',
  `currency` char(3) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `discount` float DEFAULT NULL COMMENT '折扣',
  `mtn_amount` double NOT NULL COMMENT 'MTN价格',
  `pay_type` tinyint(1) NOT NULL COMMENT '付款方式(1法币付款，2mtn付款)',
  `pay_status` tinyint(1) NOT NULL COMMENT '订单付款状态：1未付款、2已付款、3已退款, 4付款失败，5已取消',
  `pay_result` TEXT COMMENT '支付结果',
  `exchange_status` tinyint(1) NOT NOT NULL COMMENT '订单状态：1未兑换，2兑换进行中，2已兌換成功，3兑换失败',
  `exchange_result` TEXT COMMENT '兑换结果',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `created_at` (`created_at`),
  KEY `updated_at` (`updated_at`),
  KEY `pay_status` (`pay_status`),
  KEY `exchange_status` (`exchange_status`),
  UNIQUE KEY `order_id` (`order_id`),
  KEY `user_id` (`user_id`),
  KEY `category_code` (`category_code`),
  KEY `product_id` (`product_id`),
  KEY `type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;